require("colors");

import {
        atMessagesParser,
        AtMessage
} from "../lib/index";

let atMessages: AtMessage[];
let expect: string;
let test: string;

test = "test CLAC";

let rest= String.raw
`:&C,&D,&E,&F,&S,&V,&W,E,I,L,M,Q,V,X,Z,T,P,\Q,\S,\V,%V,D,A,H,O,S0,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S30,S103,S104,+FCLASS,+ICF,+IFC,+IPR,+GMI,+GMM,+GMR,+GCAP,+GSN,+DR,+D S,+WS46,+CLAC,+CCLK,+CBST,+CRLP,+CV120,+CHSN,+CSSN,+CREG,+CGREG,+CFUN,+GCAP,+CSCS,+CSTA,+CR,+CEER,+CRC,+CMEE,+CGDCONT,+CGDSCONT,+CGTFT,+CGEQREQ,+CGEQMIN,+CGQREQ,+CGQMIN,+CGEQNEG,+CGEREP,+C GPADDR,+CGCLASS,+CGSMS,+CSMS,+CMGF,+CSAS,+CRES,+CSCA,+CSMP,+CSDH,+CSCB,+FDD,+FAR,+FCL,+FIT,+ES,+ESA,+CMOD,+CVHU,+CGDATA,+CSQ,+CBC,+CPAS,+CPIN,+CMEC,+CKPD,+CIND,+CMER,+CGATT,+CGACT,+CGCMOD, +CPBS,+CPBR,+CPBF,+CPBW,+CPMS,+CNMI,+CMGL,+CMGR,+CMGS,+CMSS,+CMGW,+CMGD,+CMGC,+CNMA,+CMMS,+FTS,+FRS,+FTH,+FRH,+FTM,+FRM,+CHUP,+CCFC,+CCUG,+COPS,+CLCK,+CPWD,+CUSD,+CAOC,+CACM,+CAMM,+CPUC,+C CWA,+CHLD,+CIMI,+CGMI,+CGMM,+CGMR,+CGSN,+CNUM,+CSIM,+CRSM,+CCLK,+CLVL,+CMUT,+CLCC,+COPN,+CPOL,+CPLS,+CTZR,+CTZU,+CLAC,+CLIP,+COLP,+CDIP,+CTFR,+CLIR,$QCSIMSTAT,$QCCNMI,$QCCLR,$QCDMG,$QCDMR, $QCDNSP,$QCDNSS,$QCTER,$QCSLOT,$QCPINSTAT,$QCPDPP,$QCPDPLT,$QCPWRDN,$QCDGEN,$BREW,$QCSYSMODE,^STSF,^STGI,^STGR,^IMSICHG,^SYSINFO,^SYSCFG,^SYSCONFIG,^HS,^DTMF,^CPBR,^CPBW,^HWVER,^HVER,^DSFL OWCLR,^DSFLOWQRY,^DSFLOWRPT,^SPN,^PORTSEL,^CPIN,^SN,^EARST,^CARDLOCK,^CARDUNLOCK,^ATRECORD,^CDUR,^BOOT,^FHVER,^CURC,^FREQLOCK,^FREQPREF,^HSDPA,^CARDMODE,^U2DIAG,^PAD,^PCSCINFO,^CQI,^CVOICE ,^DDSETEX,^pcmrecord,^PCMBUFFER,^CSNR,^PNN,^OPL,^CPNN,^ADCTEMP,^RDCUST,^SETPID,^DIALMODE,^YJCX,^NDISDUP,^DHCP,^AUTHDATA,^CRPN,^ICCID,`;

atMessages = atMessagesParser([
  `\r\n+CLAC${rest}\r\n`,
  `\r\nOK\r\n`
].join(""));


expect= String.raw
`[
  {
    "raw": "\r\n+CLAC:&C,&D,&E,&F,&S,&V,&W,E,I,L,M,Q,V,X,Z,T,P,\\Q,\\S,\\V,%V,D,A,H,O,S0,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S30,S103,S104,+FCLASS,+ICF,+IFC,+IPR,+GMI,+GMM,+GMR,+GCAP,+GSN,+DR,+D S,+WS46,+CLAC,+CCLK,+CBST,+CRLP,+CV120,+CHSN,+CSSN,+CREG,+CGREG,+CFUN,+GCAP,+CSCS,+CSTA,+CR,+CEER,+CRC,+CMEE,+CGDCONT,+CGDSCONT,+CGTFT,+CGEQREQ,+CGEQMIN,+CGQREQ,+CGQMIN,+CGEQNEG,+CGEREP,+C GPADDR,+CGCLASS,+CGSMS,+CSMS,+CMGF,+CSAS,+CRES,+CSCA,+CSMP,+CSDH,+CSCB,+FDD,+FAR,+FCL,+FIT,+ES,+ESA,+CMOD,+CVHU,+CGDATA,+CSQ,+CBC,+CPAS,+CPIN,+CMEC,+CKPD,+CIND,+CMER,+CGATT,+CGACT,+CGCMOD, +CPBS,+CPBR,+CPBF,+CPBW,+CPMS,+CNMI,+CMGL,+CMGR,+CMGS,+CMSS,+CMGW,+CMGD,+CMGC,+CNMA,+CMMS,+FTS,+FRS,+FTH,+FRH,+FTM,+FRM,+CHUP,+CCFC,+CCUG,+COPS,+CLCK,+CPWD,+CUSD,+CAOC,+CACM,+CAMM,+CPUC,+C CWA,+CHLD,+CIMI,+CGMI,+CGMM,+CGMR,+CGSN,+CNUM,+CSIM,+CRSM,+CCLK,+CLVL,+CMUT,+CLCC,+COPN,+CPOL,+CPLS,+CTZR,+CTZU,+CLAC,+CLIP,+COLP,+CDIP,+CTFR,+CLIR,$QCSIMSTAT,$QCCNMI,$QCCLR,$QCDMG,$QCDMR, $QCDNSP,$QCDNSS,$QCTER,$QCSLOT,$QCPINSTAT,$QCPDPP,$QCPDPLT,$QCPWRDN,$QCDGEN,$BREW,$QCSYSMODE,^STSF,^STGI,^STGR,^IMSICHG,^SYSINFO,^SYSCFG,^SYSCONFIG,^HS,^DTMF,^CPBR,^CPBW,^HWVER,^HVER,^DSFL OWCLR,^DSFLOWQRY,^DSFLOWRPT,^SPN,^PORTSEL,^CPIN,^SN,^EARST,^CARDLOCK,^CARDUNLOCK,^ATRECORD,^CDUR,^BOOT,^FHVER,^CURC,^FREQLOCK,^FREQPREF,^HSDPA,^CARDMODE,^U2DIAG,^PAD,^PCSCINFO,^CQI,^CVOICE ,^DDSETEX,^pcmrecord,^PCMBUFFER,^CSNR,^PNN,^OPL,^CPNN,^ADCTEMP,^RDCUST,^SETPID,^DIALMODE,^YJCX,^NDISDUP,^DHCP,^AUTHDATA,^CRPN,^ICCID,\r\n",
    "id": "P_CLAC_EXEC",
    "supportedCommands": [
      "&C",
      "&D",
      "&E",
      "&F",
      "&S",
      "&V",
      "&W",
      "E",
      "I",
      "L",
      "M",
      "Q",
      "V",
      "X",
      "Z",
      "T",
      "P",
      "\\Q",
      "\\S",
      "\\V",
      "%V",
      "D",
      "A",
      "H",
      "O",
      "S0",
      "S2",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "S9",
      "S10",
      "S11",
      "S30",
      "S103",
      "S104",
      "+FCLASS",
      "+ICF",
      "+IFC",
      "+IPR",
      "+GMI",
      "+GMM",
      "+GMR",
      "+GCAP",
      "+GSN",
      "+DR",
      "+DS",
      "+WS46",
      "+CLAC",
      "+CCLK",
      "+CBST",
      "+CRLP",
      "+CV120",
      "+CHSN",
      "+CSSN",
      "+CREG",
      "+CGREG",
      "+CFUN",
      "+GCAP",
      "+CSCS",
      "+CSTA",
      "+CR",
      "+CEER",
      "+CRC",
      "+CMEE",
      "+CGDCONT",
      "+CGDSCONT",
      "+CGTFT",
      "+CGEQREQ",
      "+CGEQMIN",
      "+CGQREQ",
      "+CGQMIN",
      "+CGEQNEG",
      "+CGEREP",
      "+CGPADDR",
      "+CGCLASS",
      "+CGSMS",
      "+CSMS",
      "+CMGF",
      "+CSAS",
      "+CRES",
      "+CSCA",
      "+CSMP",
      "+CSDH",
      "+CSCB",
      "+FDD",
      "+FAR",
      "+FCL",
      "+FIT",
      "+ES",
      "+ESA",
      "+CMOD",
      "+CVHU",
      "+CGDATA",
      "+CSQ",
      "+CBC",
      "+CPAS",
      "+CPIN",
      "+CMEC",
      "+CKPD",
      "+CIND",
      "+CMER",
      "+CGATT",
      "+CGACT",
      "+CGCMOD",
      "+CPBS",
      "+CPBR",
      "+CPBF",
      "+CPBW",
      "+CPMS",
      "+CNMI",
      "+CMGL",
      "+CMGR",
      "+CMGS",
      "+CMSS",
      "+CMGW",
      "+CMGD",
      "+CMGC",
      "+CNMA",
      "+CMMS",
      "+FTS",
      "+FRS",
      "+FTH",
      "+FRH",
      "+FTM",
      "+FRM",
      "+CHUP",
      "+CCFC",
      "+CCUG",
      "+COPS",
      "+CLCK",
      "+CPWD",
      "+CUSD",
      "+CAOC",
      "+CACM",
      "+CAMM",
      "+CPUC",
      "+CCWA",
      "+CHLD",
      "+CIMI",
      "+CGMI",
      "+CGMM",
      "+CGMR",
      "+CGSN",
      "+CNUM",
      "+CSIM",
      "+CRSM",
      "+CCLK",
      "+CLVL",
      "+CMUT",
      "+CLCC",
      "+COPN",
      "+CPOL",
      "+CPLS",
      "+CTZR",
      "+CTZU",
      "+CLAC",
      "+CLIP",
      "+COLP",
      "+CDIP",
      "+CTFR",
      "+CLIR",
      "$QCSIMSTAT",
      "$QCCNMI",
      "$QCCLR",
      "$QCDMG",
      "$QCDMR",
      "$QCDNSP",
      "$QCDNSS",
      "$QCTER",
      "$QCSLOT",
      "$QCPINSTAT",
      "$QCPDPP",
      "$QCPDPLT",
      "$QCPWRDN",
      "$QCDGEN",
      "$BREW",
      "$QCSYSMODE",
      "^STSF",
      "^STGI",
      "^STGR",
      "^IMSICHG",
      "^SYSINFO",
      "^SYSCFG",
      "^SYSCONFIG",
      "^HS",
      "^DTMF",
      "^CPBR",
      "^CPBW",
      "^HWVER",
      "^HVER",
      "^DSFLOWCLR",
      "^DSFLOWQRY",
      "^DSFLOWRPT",
      "^SPN",
      "^PORTSEL",
      "^CPIN",
      "^SN",
      "^EARST",
      "^CARDLOCK",
      "^CARDUNLOCK",
      "^ATRECORD",
      "^CDUR",
      "^BOOT",
      "^FHVER",
      "^CURC",
      "^FREQLOCK",
      "^FREQPREF",
      "^HSDPA",
      "^CARDMODE",
      "^U2DIAG",
      "^PAD",
      "^PCSCINFO",
      "^CQI",
      "^CVOICE",
      "^DDSETEX",
      "^pcmrecord",
      "^PCMBUFFER",
      "^CSNR",
      "^PNN",
      "^OPL",
      "^CPNN",
      "^ADCTEMP",
      "^RDCUST",
      "^SETPID",
      "^DIALMODE",
      "^YJCX",
      "^NDISDUP",
      "^DHCP",
      "^AUTHDATA",
      "^CRPN",
      "^ICCID"
    ]
  },
  {
    "raw": "\r\nOK\r\n",
    "id": "OK",
    "isFinal": true
  }
]`;

console.assert(expect === JSON.stringify(atMessages, null, 2),
  `Fail test ${test}`.red);
console.log(`Pass test ${test}`.green);
